let educationalArray = [
  "Bachelor of Architecture-B.Arch",
  "Bachelor of Arts-B.A.",
  "Bachelor of Ayurvedic Medicine & Surgery-B.A.M.S.",
  "Bachelor of Business Administration-B.B.A.",
  "Bachelor of Commerce-B.Com.",
  "Bachelor of Computer Applications-B.C.A.",
  "Bachelor of Dental Surgery-B.D.S.",
  "Bachelor of Design-B.Des. / B.D.",
  "Bachelor of Education-B.Ed.",
  "Bachelor of Engineering / Bachelor of Technology-B.E./B.Tech.",
  "Bachelor of Fine Arts-BFA / BVA",
  "Bachelor of Fisheries Science-B.F.Sc./ B.Sc. (Fisheries).",
  "Bachelor of Homoeopathic Medicine and Surgery-B.H.M.S.",
  "Bachelor of Laws-L.L.B.",
  "Bachelor of Library Science-B.Lib. / B.Lib.Sc.",
  "Bachelor of Mass Communications-B.M.C. / B.M.M.",
  "Bachelor of Medicine and Bachelor of Surgery-M.B.B.S.",
  "Bachelor of Nursing-Bachelor of Nursing",
  "Bachelor of Pharmacy-B.Pharm / B.Pharma.",
  "Bachelor of Physical Education-B.P.Ed.",
  "Bachelor of Physiotherapy-B.P.T.",
  "Bachelor of Science-B.Sc.",
  "Bachelor of Social Work-BSW / B.A. (SW)",
  "Bachelor of Veterinary Science & Animal Husbandry-B.V.Sc. & A.H. / B.V.Sc",
  "Doctor of Medicine-M.D.",
  "Doctor of Medicine in Homoeopathy-M.D. (Homoeopathy)",
  "Doctor of Pharmacy-Pharm.D",
  "Doctor of Philosophy-Ph.D.",
  "Doctorate of Medicine-D.M.",
  "Master of Architecture-M.Arch.",
  "Master of Arts-M.A.",
  "Master of Business Administration-M.B.A.",
  "Master of Chirurgiae-M.Ch.",
  "Master of Commerce-M.Com.",
  "Master of Computer Applications-M.C.A.",
  "Master of Dental Surgery-M.D.S.",
  "Master of Design-M.Des./ M.Design.",
  "Master of Education-M.Ed.",
  "Master of Engineering / Master of Technology-M.E./ M.Tech.",
  "Master of Fine Arts-MFA / MVA",
  "Master of Laws-L.L.M.",
  "Master of Library Science-M.Lib./ M.Lib.Sc.",
  "Master of Mass Communications / Mass Media-M.M.C / M.M.M.",
  "Master of Pharmacy-M.Pharm",
  "Master of Philosophy-M.Phil.",
  "Master of Physical Education-M.P.Ed. / M.P.E.",
  "Master of Physiotherapy-M.P.T.",
  "Master of Science-M.Sc.",
  "Master of Social Work / Master of Arts in Social Work-M.S.W. / M.A. (SW)",
  "Master of Science in Agriculture-M.Sc. (Agriculture)",
  "Master of Surgery-M.S.",
  "Master of Veterinary Science-M.V.Sc.",
  "Phd-Phd",
  "Diploma-Diploma",
  "Class 12th-Class 12th/PUC",
  "Class 10th-Class 10th",
];

export default educationalArray;
