const technicalSkillsConstantArray = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Angular",
  "Vue.js",
  "jQuery",
  "Bootstrap",
  "Sass",
  "Tailwind CSS",
  "Node.js",
  "Python",
  "Java",
  "Ruby",
  "PHP",
  "Go",
  ".NET",
  "Rust",
  "Kotlin",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot ",
  "Ruby on Rails",
  "Laravel",
  "Symfony",
  "ASP.NET",
  "Ktor",
  "React Native",
  "Flutter",
  "Ionic",
  "Xamarin",
  "NativeScript",
  "PhoneGap/Cordova",
  "Framework7",
  "Onsen UI",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Microsoft SQL Server",
  "Oracle Database",
  "SQLite",
  "Redis",
  "Cassandra",
  "Firebase",
  "Elasticsearch",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "IBM Cloud",
  "Oracle Cloud Infrastructure (OCI)",
  "Alibaba Cloud",
  "DigitalOcean",
  "Heroku",
  "Salesforce Cloud",
  "VMware Cloud",
];

export default technicalSkillsConstantArray;
